# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    binary: wifitui
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - formats: [tar.gz]
    # Make the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ tolower .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc

nfpms:
  - id: wifitui
    maintainer: 'Andrey Petrov'
    description: 'Fast featureful friendly wifi terminal UI. 🛜✨'
    homepage: 'https://github.com/shazow/wifitui'
    license: 'MIT'
    formats:
      - deb
      - rpm
      - archlinux
    file_name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ tolower .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

signs:
  - artifacts: all
    args: ["--batch", "--local-user",  "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
