name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.25'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -v -o wifitui-${{ matrix.goos }}-${{ matrix.goarch }} .
          tar -czvf wifitui-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz wifitui-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wifitui-${{ matrix.goos }}-${{ matrix.goarch }}
          path: wifitui-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: List files
        run: ls -R artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            artifacts/wifitui-linux-amd64/wifitui-linux-amd64.tar.gz
            artifacts/wifitui-darwin-amd64/wifitui-darwin-amd64.tar.gz
